import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export const header = `// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by scripts/generate.ts\n\n`;

export function sanitizeId(input: string): string {
  return input.replace(/[^a-zA-Z0-9_]/g, '_');
}

export const writeLinesToFile = async (
  baseDir: string,
  elementName: string,
  filename: string,
  lines: string[],
): Promise<void> => {
  const elementDir = join(baseDir, elementName);
  await mkdir(elementDir, { recursive: true });

  await writeToFile(join(elementDir, filename), lines.join('\n'));
};

export const writeToFile = async (
  filePath: string,
  content: string,
): Promise<void> => {
  await writeFile(filePath, content, 'utf8');
};
